#datasource
spring:
  datasource:
    name: water
    url: jdbc:mysql://localhost:3306/water?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#Hikaricp config
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 30
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    com.water.dao: debug


