#datasource
spring:
  datasource:
    name: water
    url: jdbc:mysql://10.100.11.137/water
    username: root
    password: QVkiHClEnDfSW4o9
    driver-class-name: com.mysql.jdbc.Driver
#Hikaricp config
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 30
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
